module hdmi_top (
    input  wire clk,          // 27MHz onboard clock (pin 52)
    input  wire rst_n_btn,    // onboard button S1, active-low (pin 4)
    output wire tmds_clk_p, tmds_clk_n,
    output wire [2:0] tmds_d_p, tmds_d_n
);


    // ---------------------------------------------------------
    // Clocks
    // serial_clk = 5 x pixel_clk  (generated by the rPLL from 27MHz)
    // pixel_clk  = serial_clk / 5 (generated by CLKDIV)
    // ---------------------------------------------------------
    wire serial_clk;   // target ~126MHz
    wire pixel_clk;    // target ~25.2MHz
    wire pll_lock;

    Gowin_rPLL rpll_inst (
        .clkout (serial_clk),
        .lock   (pll_lock),
        .clkin  (clk)
    );

    wire clk_rst_n = rst_n_btn & pll_lock;

    CLKDIV #(
        .DIV_MODE("5"),
        .GSREN("false")
    ) u_clkdiv (
        .CLKOUT (pixel_clk),
        .HCLKIN (serial_clk),
        .RESETN (clk_rst_n),
        .CALIB  (1'b0)
    );

    // ---------------------------------------------------------
    // Video timing
    // ---------------------------------------------------------
    wire hsync, vsync, active;
    wire [9:0] x, y;

    video_timing u_timing (
        .pixel_clk (pixel_clk),
        .rst_n     (clk_rst_n),
        .hsync     (hsync),
        .vsync     (vsync),
        .active    (active),
        .x         (x),
        .y         (y)
    );

    // ---------------------------------------------------------
    // rutraCPU + rutraGPU
    // ---------------------------------------------------------
    wire cpu_reset = ~clk_rst_n;   // active-high reset for CPU/GPU

    wire [7:0]  cpu_pc;
    wire [11:0] cpu_instr;
    wire [7:0]  cpu_acc;
    wire [7:0]  cpu_out_data;
    wire        cpu_out_valid;
    wire        cpu_out_is_char;
    wire        cpu_halted;

    rutracpu_rom u_rom (
        .address     (cpu_pc),
        .instruction (cpu_instr)
    );

    rutracpu u_cpu (
        .clk         (pixel_clk),
        .reset       (cpu_reset),
        .instruction (cpu_instr),
        .pc          (cpu_pc),
        .acc         (cpu_acc),
        .out_data    (cpu_out_data),
        .out_valid   (cpu_out_valid),
        .out_is_char (cpu_out_is_char),
        .halted      (cpu_halted)
    );

    // Scale the 16x16 framebuffer up to fill the 640x480 active area
    wire [3:0] vid_x = x / 10'd40;   // 640 / 16 = 40 px 
    wire [3:0] vid_y = y / 10'd30;   // 480 / 16 = 30 px 
    wire       vid_pixel;
    wire       gpu_consumed;
    wire       gpu_present_pulse;

    rutragpu u_gpu (
        .clk           (pixel_clk),
        .reset         (cpu_reset),
        .in_valid      (cpu_out_valid),
        .in_is_char    (cpu_out_is_char),
        .in_data       (cpu_out_data),
        .consumed      (gpu_consumed),
        .present_pulse (gpu_present_pulse),
        .vid_x         (vid_x),
        .vid_y         (vid_y),
        .vid_pixel     (vid_pixel)
    );

    // ---------------------------------------------------------
    // white if on, blueish black if off
    // ---------------------------------------------------------
    reg [7:0] red, green, blue;
    always @(posedge pixel_clk) begin
        if (active) begin
            if (vid_pixel)
                {red, green, blue} <= {8'hFF, 8'hFF, 8'hFF}; // white
            else
                {red, green, blue} <= {8'h00, 8'h00, 8'h20}; // dim blue
        end else begin
            {red, green, blue} <= 24'h0;
        end
    end

    // ---------------------------------------------------------
    // DVI TX IP core — handles TMDS encoding + serialization +
    // TLVDS output buffering for all four channels internally.
    // ---------------------------------------------------------
    DVI_TX_Top u_dvi_tx (
        .I_rst_n      (clk_rst_n),
        .I_serial_clk (serial_clk),
        .I_rgb_clk    (pixel_clk),
        .I_rgb_vs     (vsync),
        .I_rgb_hs     (hsync),
        .I_rgb_de     (active),
        .I_rgb_r      (red),
        .I_rgb_g      (green),
        .I_rgb_b      (blue),
        .O_tmds_clk_p (tmds_clk_p),
        .O_tmds_clk_n (tmds_clk_n),
        .O_tmds_data_p(tmds_d_p),
        .O_tmds_data_n(tmds_d_n)
    );

endmodule