module hdmi_top (
    input  wire clk,          // 27MHz onboard clock (pin 52)
    input  wire rst_n_btn,    // onboard button S1, active-low (pin 4)
    output wire tmds_clk_p, tmds_clk_n,
    output wire [2:0] tmds_d_p, tmds_d_n
);


    // ---------------------------------------------------------
    // Clocks
    // serial_clk = 5 x pixel_clk  (generated by the rPLL from 27MHz)
    // pixel_clk  = serial_clk / 5 (generated by CLKDIV)
    // ---------------------------------------------------------
    wire serial_clk;   // target ~126MHz
    wire pixel_clk;    // target ~25.2MHz
    wire pll_lock;

    Gowin_rPLL rpll_inst (
        .clkout (serial_clk),
        .lock   (pll_lock),
        .clkin  (clk)
    );

    wire clk_rst_n = rst_n_btn & pll_lock;

    CLKDIV #(
        .DIV_MODE("5"),
        .GSREN("false")
    ) u_clkdiv (
        .CLKOUT (pixel_clk),
        .HCLKIN (serial_clk),
        .RESETN (clk_rst_n),
        .CALIB  (1'b0)
    );

    // ---------------------------------------------------------
    // Video timing
    // ---------------------------------------------------------
    wire hsync, vsync, active;
    wire [9:0] x, y;

    video_timing u_timing (
        .pixel_clk (pixel_clk),
        .rst_n     (clk_rst_n),
        .hsync     (hsync),
        .vsync     (vsync),
        .active    (active),
        .x         (x),
        .y         (y)
    );

    // ---------------------------------------------------------
    // Test pattern: 8 vertical color bars across the screen
    // ---------------------------------------------------------
    reg [7:0] red, green, blue;
    always @(posedge pixel_clk) begin
        if (active) begin
            case (x/80) // 640/8=80
                3'd0: {red,green,blue} <= {8'hFF,8'hFF,8'hFF}; // white
                3'd1: {red,green,blue} <= {8'hFF,8'hFF,8'h00}; // yellow
                3'd2: {red,green,blue} <= {8'h00,8'hFF,8'hFF}; // cyan
                3'd3: {red,green,blue} <= {8'h00,8'hFF,8'h00}; // green
                3'd4: {red,green,blue} <= {8'hFF,8'h00,8'hFF}; // magenta
                3'd5: {red,green,blue} <= {8'hFF,8'h00,8'h00}; // red
                3'd6: {red,green,blue} <= {8'h00,8'h00,8'hFF}; // blue
                default: {red,green,blue} <= {8'h00,8'h00,8'h00}; // black
            endcase
        end else begin
            {red,green,blue} <= 24'h0;
        end
    end

    // ---------------------------------------------------------
    // DVI TX IP core — handles TMDS encoding + serialization +
    // TLVDS output buffering for all four channels internally.
    // ---------------------------------------------------------
    DVI_TX_Top u_dvi_tx (
        .I_rst_n      (clk_rst_n),
        .I_serial_clk (serial_clk),
        .I_rgb_clk    (pixel_clk),
        .I_rgb_vs     (vsync),
        .I_rgb_hs     (hsync),
        .I_rgb_de     (active),
        .I_rgb_r      (red),
        .I_rgb_g      (green),
        .I_rgb_b      (blue),
        .O_tmds_clk_p (tmds_clk_p),
        .O_tmds_clk_n (tmds_clk_n),
        .O_tmds_data_p(tmds_d_p),
        .O_tmds_data_n(tmds_d_n)
    );

endmodule