module hdmi_top (
    input  wire clk,          // 27MHz onboard clock (pin 52)
    input  wire rst_n_btn,    // onboard button S1, active-low (pin 4)
    output wire tmds_clk,
    output wire [2:0] tmds_d
);

    wire rst_n = rst_n_btn;

    // ---------------------------------------------------------
    // Clocks
    // serial_clk = 5 x pixel_clk  (generated by the rPLL from 27MHz)
    // pixel_clk  = serial_clk / 5 (generated by CLKDIV)
    // ---------------------------------------------------------
    wire serial_clk;   // target ~126MHz
    wire pixel_clk;    // target ~25.2MHz
    wire pll_lock;

    Gowin_rPLL rpll_inst (
        .clkout (serial_clk),
        .lock   (pll_lock),
        .clkin  (clk)
    );

    wire clk_rst_n = rst_n & pll_lock;

    CLKDIV #(
        .DIV_MODE("5"),
        .GSREN("false")
    ) u_clkdiv (
        .CLKOUT (pixel_clk),
        .HCLKIN (serial_clk),
        .RESETN (clk_rst_n),
        .CALIB  (1'b0)
    );

    // ---------------------------------------------------------
    // Video timing
    // ---------------------------------------------------------
    wire hsync, vsync, active;
    wire [9:0] x, y;

    video_timing u_timing (
        .pixel_clk (pixel_clk),
        .rst_n     (clk_rst_n),
        .hsync     (hsync),
        .vsync     (vsync),
        .active    (active),
        .x         (x),
        .y         (y)
    );

    // ---------------------------------------------------------
    // Test pattern: 8 vertical color bars across the screen
    // ---------------------------------------------------------
    reg [7:0] red, green, blue;
    always @(posedge pixel_clk) begin
        if (active) begin
            case (x/80) // 640/8=80
                3'd0: {red,green,blue} <= {8'hFF,8'hFF,8'hFF}; // white
                3'd1: {red,green,blue} <= {8'hFF,8'hFF,8'h00}; // yellow
                3'd2: {red,green,blue} <= {8'h00,8'hFF,8'hFF}; // cyan
                3'd3: {red,green,blue} <= {8'h00,8'hFF,8'h00}; // green
                3'd4: {red,green,blue} <= {8'hFF,8'h00,8'hFF}; // magenta
                3'd5: {red,green,blue} <= {8'hFF,8'h00,8'h00}; // red
                3'd6: {red,green,blue} <= {8'h00,8'h00,8'hFF}; // blue
                default: {red,green,blue} <= {8'h00,8'h00,8'h00}; // black
            endcase
        end else begin
            {red,green,blue} <= 24'h0;
        end
    end

    // ---------------------------------------------------------
    // TMDS encoders — one per channel
    // HDMI convention: channel 0 = blue (carries hsync/vsync in blanking),
    // channel 1 = green, channel 2 = red
    // ---------------------------------------------------------
    wire [9:0] tmds_blue, tmds_green, tmds_red;

    tmds_encoder enc_b (
        .clk(pixel_clk), .rst_n(clk_rst_n),
        .pixel_data(blue), .control_bits({vsync,hsync}), .data_enable(active), .tmds_out(tmds_blue)
    );
    tmds_encoder enc_g (
        .clk(pixel_clk), .rst_n(clk_rst_n),
        .pixel_data(green), .control_bits(2'b00), .data_enable(active), .tmds_out(tmds_green)
    );
    tmds_encoder enc_r (
        .clk(pixel_clk), .rst_n(clk_rst_n),
        .pixel_data(red), .control_bits(2'b00), .data_enable(active), .tmds_out(tmds_red)
    );

    // ---------------------------------------------------------
    // Serializers: 10-bit parallel -> 1-bit serial per channel.
    // OSER10 uses PCLK (pixel clock) + FCLK (5x serial clock) with DDR
    // internally to shift out all 10 bits per pixel-clock period.
    // The clock channel just repeats a fixed 1111100000 pattern.
    // ---------------------------------------------------------
    OSER10 oser_clk (
        .Q(tmds_clk),
        .D0(1'b1),.D1(1'b1),.D2(1'b1),.D3(1'b1),.D4(1'b1),
        .D5(1'b0),.D6(1'b0),.D7(1'b0),.D8(1'b0),.D9(1'b0),
        .PCLK(pixel_clk), .FCLK(serial_clk), .RESET(~clk_rst_n)
    );

    OSER10 oser_d0 (
        .Q(tmds_d[0]),
        .D0(tmds_blue[0]),.D1(tmds_blue[1]),.D2(tmds_blue[2]),.D3(tmds_blue[3]),.D4(tmds_blue[4]),
        .D5(tmds_blue[5]),.D6(tmds_blue[6]),.D7(tmds_blue[7]),.D8(tmds_blue[8]),.D9(tmds_blue[9]),
        .PCLK(pixel_clk), .FCLK(serial_clk), .RESET(~clk_rst_n)
    );

    OSER10 oser_d1 (
        .Q(tmds_d[1]),
        .D0(tmds_green[0]),.D1(tmds_green[1]),.D2(tmds_green[2]),.D3(tmds_green[3]),.D4(tmds_green[4]),
        .D5(tmds_green[5]),.D6(tmds_green[6]),.D7(tmds_green[7]),.D8(tmds_green[8]),.D9(tmds_green[9]),
        .PCLK(pixel_clk), .FCLK(serial_clk), .RESET(~clk_rst_n)
    );

    OSER10 oser_d2 (
        .Q(tmds_d[2]),
        .D0(tmds_red[0]),.D1(tmds_red[1]),.D2(tmds_red[2]),.D3(tmds_red[3]),.D4(tmds_red[4]),
        .D5(tmds_red[5]),.D6(tmds_red[6]),.D7(tmds_red[7]),.D8(tmds_red[8]),.D9(tmds_red[9]),
        .PCLK(pixel_clk), .FCLK(serial_clk), .RESET(~clk_rst_n)
    );

endmodule