module rutra_top (
    input  wire clk,          // 27MHz onboard clock (pin 52)
    input  wire rst_n_btn,    // onboard button S1, active-low (pin 4)
    output wire uart_tx,      // UART to PC via onboard USB bridge (pin 17)
    input  wire uart_rx,      // UART from PC via onboard USB bridge (pin 18)
    output wire tmds_clk_p, tmds_clk_n,
    output wire [2:0] tmds_d_p, tmds_d_n
);


    // ---------------------------------------------------------
    // Clocks
    // serial_clk = 5 x pixel_clk  (generated by the rPLL from 27MHz)
    // pixel_clk  = serial_clk / 5 (generated by CLKDIV)
    // ---------------------------------------------------------
    wire serial_clk;   // target ~126MHz
    wire pixel_clk;    // target ~25.2MHz
    wire pll_lock;

    Gowin_rPLL rpll_inst (
        .clkout (serial_clk),
        .lock   (pll_lock),
        .clkin  (clk)
    );

    wire clk_rst_n = rst_n_btn & pll_lock;

    CLKDIV #(
        .DIV_MODE("5"),
        .GSREN("false")
    ) u_clkdiv (
        .CLKOUT (pixel_clk),
        .HCLKIN (serial_clk),
        .RESETN (clk_rst_n),
        .CALIB  (1'b0)
    );

    // ---------------------------------------------------------
    // Video timing
    // ---------------------------------------------------------
    wire hsync, vsync, active;
    wire [9:0] x, y;

    video_timing u_timing (
        .pixel_clk (pixel_clk),
        .rst_n     (clk_rst_n),
        .hsync     (hsync),
        .vsync     (vsync),
        .active    (active),
        .x         (x),
        .y         (y)
    );

    // ---------------------------------------------------------
    // rutraCPU + rutraGPU
    // ---------------------------------------------------------
    // Bootloader holds the CPU/GPU in reset while a program is being loaded
    wire        boot_hold;
    wire        cpu_reset = ~clk_rst_n | boot_hold;   // active-high reset for CPU/GPU

    wire [7:0]  cpu_pc;
    wire [15:0] cpu_instr;
    wire [7:0]  cpu_acc;
    wire [7:0]  cpu_out_data;
    wire        cpu_out_valid;
    wire        cpu_out_is_char;
    wire        cpu_halted;
    wire        gpu_present_pulse;
    wire        vid_pixel;

    wire        uart_busy;
    wire        cpu_consumed = ~uart_busy;

    uart_tx #(.CLK_HZ(25_200_000), .BAUD(115200)) u_uart (
        .clk   (pixel_clk),
        .rst_n (clk_rst_n),
        .data  (cpu_out_data),
        .start (cpu_out_valid & ~uart_busy),
        .tx    (uart_tx),
        .busy  (uart_busy)
    );

    wire [3:0]  gpu_cmd;
    wire [7:0]  gpu_arg;
    wire        gpu_start;
    wire        gpu_done;

    wire [9:0] vid_x_div = x / 10'd10;
    wire [9:0] vid_y_div = y / 10'd10;
    wire [5:0] vid_x = vid_x_div[5:0];
    wire [5:0] vid_y = vid_y_div[5:0];

    // ---------------------------------------------------------
    // UART bootloader: receives program, writes it into ROM
    // ---------------------------------------------------------
    wire [7:0]  rx_data;
    wire        rx_valid;
    wire        rom_we;
    wire [7:0]  rom_waddr;
    wire [15:0] rom_wdata;

    uart_rx #(.CLK_HZ(25_200_000), .BAUD(115200)) u_uart_rx (
        .clk   (pixel_clk),
        .rst_n (clk_rst_n),
        .rx    (uart_rx),
        .data  (rx_data),
        .valid (rx_valid)
    );

    rutra_boot u_boot (
        .clk       (pixel_clk),
        .rst_n     (clk_rst_n),
        .rx_data   (rx_data),
        .rx_valid  (rx_valid),
        .rom_we    (rom_we),
        .rom_addr  (rom_waddr),
        .rom_wdata (rom_wdata),
        .cpu_hold  (boot_hold)
    );

    rutracpu_rom u_rom (
        .clk         (pixel_clk),
        .we          (rom_we),
        .waddr       (rom_waddr),
        .wdata       (rom_wdata),
        .address     (cpu_pc),
        .instruction (cpu_instr)
    );

    rutracpu u_cpu (
        .clk         (pixel_clk),
        .reset       (cpu_reset),
        .instruction (cpu_instr),
        .consumed    (cpu_consumed),
        .pc          (cpu_pc),
        .acc         (cpu_acc),
        .out_data    (cpu_out_data),
        .out_valid   (cpu_out_valid),
        .out_is_char (cpu_out_is_char),
        .halted      (cpu_halted),
        .gpu_cmd     (gpu_cmd),
        .gpu_arg     (gpu_arg),
        .gpu_start   (gpu_start),
        .gpu_done    (gpu_done)
    );

    rutragpu u_gpu (
        .clk           (pixel_clk),
        .reset         (cpu_reset),
        .cmd           (gpu_cmd),
        .arg           (gpu_arg),
        .start         (gpu_start),
        .done          (gpu_done),
        .present_pulse (gpu_present_pulse),
        .vid_x         (vid_x),
        .vid_y         (vid_y),
        .vid_pixel     (vid_pixel)
    );

    // ---------------------------------------------------------
    // white if on, blueish black if off
    // ---------------------------------------------------------
    reg [7:0] red, green, blue;
    always @(posedge pixel_clk) begin
        if (active) begin
            if (vid_pixel)
                {red, green, blue} <= {8'hFF, 8'hFF, 8'hFF}; // white
            else
                {red, green, blue} <= {8'h00, 8'h00, 8'h20}; // dim blue
        end else begin
            {red, green, blue} <= 24'h0;
        end
    end

    // ---------------------------------------------------------
    // DVI TX IP core — handles TMDS encoding + serialization +
    // TLVDS output buffering for all four channels internally.
    // ---------------------------------------------------------
    DVI_TX_Top u_dvi_tx (
        .I_rst_n      (clk_rst_n),
        .I_serial_clk (serial_clk),
        .I_rgb_clk    (pixel_clk),
        .I_rgb_vs     (vsync),
        .I_rgb_hs     (hsync),
        .I_rgb_de     (active),
        .I_rgb_r      (red),
        .I_rgb_g      (green),
        .I_rgb_b      (blue),
        .O_tmds_clk_p (tmds_clk_p),
        .O_tmds_clk_n (tmds_clk_n),
        .O_tmds_data_p(tmds_d_p),
        .O_tmds_data_n(tmds_d_n)
    );

endmodule